Repository ConorMFinn/CO600-SeriousCyberSec, pull requests merged in 2020-12, with the labels that each got.

#29 Add desk and Sherry Assets
  assets/characters/sherry/sherry_animate.gif
  assets/characters/sherry/sherry_back.png
  assets/characters/sherry/sherry_front.png
  assets/characters/sherry/sherry_left.png
  assets/characters/sherry/sherry_right.png
  assets/items/desk.png
  assets/psd/desk.psd
  assets/psd/sherry.psd
  assets/psd/sherry_animate.psd
Labels: enhancement

#27 Add carpet and wall tiles for the hall
  assets/tiles/carpetTile.png
  assets/tiles/wallTiles.png
Labels: enhancement

#31 Add door and wall panel
  assets/doors.png
  assets/wallPanel.png
Labels: enhancement

#32 Create inital unity project with assets
  assets/characters/sherry/sherry.png
  assets/psd/sherry.psd
  project/sherLOCKED/.gitignore
  project/sherLOCKED/Assets/Characters.meta
  project/sherLOCKED/Assets/Characters/sherry.png
  project/sherLOCKED/Assets/Characters/sherry.png.meta
  project/sherLOCKED/Assets/Objects.meta
  project/sherLOCKED/Assets/Objects/desk.png
  project/sherLOCKED/Assets/Objects/desk.png.meta
  project/sherLOCKED/Assets/Scenes.meta
  project/sherLOCKED/Assets/Scenes/SampleScene.unity
  project/sherLOCKED/Assets/Scenes/SampleScene.unity.meta
  project/sherLOCKED/Assets/Tiles.meta
  project/sherLOCKED/Assets/Tiles/carpetTile.png
  project/sherLOCKED/Assets/Tiles/carpetTile.png.meta
  project/sherLOCKED/Assets/Tiles/floor.asset
  project/sherLOCKED/Assets/Tiles/floor.asset.meta
  project/sherLOCKED/Assets/Tiles/floors.prefab
  project/sherLOCKED/Assets/Tiles/floors.prefab.meta
  project/sherLOCKED/Assets/Tiles/wallTiles.png
  project/sherLOCKED/Assets/Tiles/wallTiles.png.meta
  project/sherLOCKED/Assets/Tiles/wall_plain.asset
  project/sherLOCKED/Assets/Tiles/wall_plain.asset.meta
  project/sherLOCKED/Assets/Tiles/wall_skirt.asset
  project/sherLOCKED/Assets/Tiles/wall_skirt.asset.meta
  project/sherLOCKED/Assets/Tiles/walls.prefab
  project/sherLOCKED/Assets/Tiles/walls.prefab.meta
  project/sherLOCKED/Packages/manifest.json
  project/sherLOCKED/Packages/packages-lock.json
  project/sherLOCKED/ProjectSettings/AudioManager.asset
  project/sherLOCKED/ProjectSettings/ClusterInputManager.asset
  project/sherLOCKED/ProjectSettings/DynamicsManager.asset
  project/sherLOCKED/ProjectSettings/EditorBuildSettings.asset
  project/sherLOCKED/ProjectSettings/EditorSettings.asset
  project/sherLOCKED/ProjectSettings/GraphicsSettings.asset
  project/sherLOCKED/ProjectSettings/InputManager.asset
  project/sherLOCKED/ProjectSettings/NavMeshAreas.asset
  project/sherLOCKED/ProjectSettings/NetworkManager.asset
  project/sherLOCKED/ProjectSettings/PackageManagerSettings.asset
  project/sherLOCKED/ProjectSettings/Physics2DSettings.asset
  project/sherLOCKED/ProjectSettings/PresetManager.asset
  project/sherLOCKED/ProjectSettings/ProjectSettings.asset
  project/sherLOCKED/ProjectSettings/ProjectVersion.txt
  project/sherLOCKED/ProjectSettings/QualitySettings.asset
  project/sherLOCKED/ProjectSettings/TagManager.asset
  project/sherLOCKED/ProjectSettings/TimeManager.asset
  project/sherLOCKED/ProjectSettings/UnityConnectSettings.asset
  project/sherLOCKED/ProjectSettings/VFXManager.asset
  project/sherLOCKED/ProjectSettings/XRSettings.asset
Labels: enhancement

#33 Fix resolution of assets
  project/sherLOCKED/Assets/Characters/sherry.png.meta
  project/sherLOCKED/Assets/Objects/desk.png.meta
  project/sherLOCKED/Assets/Scenes/SampleScene.unity
  project/sherLOCKED/Assets/Tiles/floor.asset
Labels: bug

#39 Add Sherry to the Scene and Add Movement Controls
  project/sherLOCKED/.vscode/settings.json
  project/sherLOCKED/Assets/Scenes/SampleScene.unity
  project/sherLOCKED/Assets/Scripts.meta
  project/sherLOCKED/Assets/Scripts/Sherry.meta
  project/sherLOCKED/Assets/Scripts/Sherry/SherryMovement.cs
  project/sherLOCKED/Assets/Scripts/Sherry/SherryMovement.cs.meta
  project/sherLOCKED/ProjectSettings/InputManager.asset
  project/sherLOCKED/ProjectSettings/QualitySettings.asset
Labels: enhancement

#42 Allow object interaction
  project/sherLOCKED/Assets/Characters/sherry_b1.prefab
  project/sherLOCKED/Assets/Characters/sherry_b1.prefab.meta
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Scripts/Sherry/SherryInteract.cs
  project/sherLOCKED/Assets/Scripts/Sherry/SherryInteract.cs.meta
  project/sherLOCKED/ProjectSettings/TagManager.asset
Labels: enhancement

#41 Add Animation to Sherry's Movement
  project/sherLOCKED/Assets/Animations.meta
  project/sherLOCKED/Assets/Animations/sherry_ac.controller
  project/sherLOCKED/Assets/Animations/sherry_ac.controller.meta
  project/sherLOCKED/Assets/Animations/sherry_east.anim
  project/sherLOCKED/Assets/Animations/sherry_east.anim.meta
  project/sherLOCKED/Assets/Animations/sherry_east_idle.anim
  project/sherLOCKED/Assets/Animations/sherry_east_idle.anim.meta
  project/sherLOCKED/Assets/Animations/sherry_north.anim
  project/sherLOCKED/Assets/Animations/sherry_north.anim.meta
  project/sherLOCKED/Assets/Animations/sherry_north_idle.anim
  project/sherLOCKED/Assets/Animations/sherry_north_idle.anim.meta
  project/sherLOCKED/Assets/Animations/sherry_south.anim
  project/sherLOCKED/Assets/Animations/sherry_south.anim.meta
  project/sherLOCKED/Assets/Animations/sherry_south_idle.anim
  project/sherLOCKED/Assets/Animations/sherry_south_idle.anim.meta
  project/sherLOCKED/Assets/Animations/sherry_west.anim
  project/sherLOCKED/Assets/Animations/sherry_west.anim.meta
  project/sherLOCKED/Assets/Animations/sherry_west_idle.anim
  project/sherLOCKED/Assets/Animations/sherry_west_idle.anim.meta
  project/sherLOCKED/Assets/Rooms/Hall_BACKUP_8453.unity
  project/sherLOCKED/Assets/Rooms/Hall_BACKUP_8453.unity.meta
  project/sherLOCKED/Assets/Rooms/Hall_BASE_8453.unity
  project/sherLOCKED/Assets/Rooms/Hall_BASE_8453.unity.meta
  project/sherLOCKED/Assets/Rooms/Hall_LOCAL_8453.unity
  project/sherLOCKED/Assets/Rooms/Hall_LOCAL_8453.unity.meta
  project/sherLOCKED/Assets/Rooms/Hall_REMOTE_8453.unity
  project/sherLOCKED/Assets/Rooms/Hall_REMOTE_8453.unity.meta
  project/sherLOCKED/Assets/Scenes/SampleScene.unity
  project/sherLOCKED/Assets/Scenes/SampleScene.unity.meta
  project/sherLOCKED/Assets/Scripts/Sherry/SherryMovement.cs
Labels: enhancement

#49 Remove unneeded git files
  project/sherLOCKED/Assets/Rooms/Hall_BACKUP_8453.unity
  project/sherLOCKED/Assets/Rooms/Hall_BACKUP_8453.unity.meta
  project/sherLOCKED/Assets/Rooms/Hall_BASE_8453.unity
  project/sherLOCKED/Assets/Rooms/Hall_BASE_8453.unity.meta
  project/sherLOCKED/Assets/Rooms/Hall_LOCAL_8453.unity
  project/sherLOCKED/Assets/Rooms/Hall_LOCAL_8453.unity.meta
  project/sherLOCKED/Assets/Rooms/Hall_REMOTE_8453.unity
  project/sherLOCKED/Assets/Rooms/Hall_REMOTE_8453.unity.meta
Labels: bug, high priority

#46 Added collision detection
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Scripts/Sherry/SherryMovement.cs
  project/sherLOCKED/ProjectSettings/TagManager.asset
Labels: enhancement, high priority
