Repository ConorMFinn/CO600-SeriousCyberSec, pull requests merged in 2021-02, with the labels that each got.

#112 Create participant information sheet
  docs/ethics/participantInformation.docx
  docs/ethics/~$rticipantInformation.docx
Labels: documentation

#114 Created full application
  docs/ethics/fullApplication.docx
Labels: documentation

#113 Create consent form
  docs/ethics/consentForm.docx
Labels: documentation

#115 Add minutes for 2021-02-02
  docs/meetings/2021-02-02_MeetingMinutes.md
Labels: documentation

#120 Updated question plan
  docs/planning/QuestionPlan.md
Labels: documentation

#117 Add research proposal RE #103
  docs/ethics/researchProposal.docx
Labels: documentation

#111 Add Level Manager
  project/sherLOCKED/Assets/Rooms/MainMenu.unity
  project/sherLOCKED/Assets/Rooms/_preload.unity
  project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
  project/sherLOCKED/Assets/Scripts/_preload/LevelManager.cs
  project/sherLOCKED/Assets/Scripts/_preload/LevelManager.cs.meta
  project/sherLOCKED/Assets/Scripts/_preload/ScoreManager.cs
  project/sherLOCKED/ProjectSettings/TagManager.asset
Labels: UI, enhancement, gameplay

#124 Updated questions in game case 1
  docs/planning/QuestionPlan.md
  project/sherLOCKED/Assets/Rooms/Ballroom.unity
  project/sherLOCKED/Assets/Rooms/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Rooms/Library.unity
Labels: assets, documentation, gameplay, interactions

#123 Door interactions are object oriented
  project/sherLOCKED/Assets/Rooms/Ballroom.unity
  project/sherLOCKED/Assets/Rooms/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Rooms/Library.unity
  project/sherLOCKED/Assets/Scripts/Objects/DoorInteraction.cs
Labels: interactions

#109 Added case 2 questions to the server room
  project/sherLOCKED/Assets/Objects/deadFlower.png
  project/sherLOCKED/Assets/Objects/deadFlower.png.meta
  project/sherLOCKED/Assets/Objects/keypad.png
  project/sherLOCKED/Assets/Objects/keypad.png.meta
  project/sherLOCKED/Assets/Rooms/MainMenu.unity
  project/sherLOCKED/Assets/Rooms/ServerRoom.unity
  project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
Labels: gameplay, interactions

#127 Fix intuition reset
  project/sherLOCKED/Assets/Scripts/_preload/ScoreManager.cs
Labels: bug, gameplay, interactions

#128 Encourage the player to talk to Ginny
  project/sherLOCKED/Assets/Characters/sherry_b1.prefab
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Scripts/HallStart.cs
  project/sherLOCKED/Assets/Scripts/UI/TextBoxController.cs
Labels: enhancement, interactions

#138 Changed the shading of the floors
  project/sherLOCKED/Assets/Objects/deadFlower.png
  project/sherLOCKED/Assets/Tiles/ballroom_carpet.png
  project/sherLOCKED/Assets/Tiles/carpetTile.png
  project/sherLOCKED/Assets/Tiles/dining_carpet.png
  project/sherLOCKED/Assets/Tiles/library_carpet.png
  project/sherLOCKED/Assets/Tiles/serverFloorTile.png
Labels: assets

#141 Question Feedback Added
  project/sherLOCKED/Assets/Rooms/Ballroom.unity
  project/sherLOCKED/Assets/Rooms/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Rooms/Library.unity
  project/sherLOCKED/Assets/Rooms/MainMenu.unity
  project/sherLOCKED/Assets/Rooms/ServerRoom.unity
  project/sherLOCKED/Assets/Scripts/Objects/ObjectInteraction.cs
Labels: enhancement, high priority, interactions

#140 Fix intro appearing multiple times
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Scripts/HallStart.cs
Labels: bug, gameplay, high priority

#136 Fix game not ending if last question wrong
  project/sherLOCKED/Assets/Rooms/MainMenu.unity
  project/sherLOCKED/Assets/Scripts/_preload/QuestionManager.cs
  project/sherLOCKED/Assets/Scripts/_preload/ScoreManager.cs
Labels: bug, gameplay

#143 Replace 'level' with 'case'
  project/sherLOCKED/Assets/Rooms/MainMenu.unity
Labels: bug

#145 Created Case 4
  project/sherLOCKED/Assets/Animations/Ginny/npc_ac.controller
  project/sherLOCKED/Assets/Rooms/Level1.meta
  project/sherLOCKED/Assets/Rooms/Level1/Ballroom.unity
  project/sherLOCKED/Assets/Rooms/Level1/Ballroom.unity.meta
  project/sherLOCKED/Assets/Rooms/Level1/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Level1/DiningRoom.unity.meta
  project/sherLOCKED/Assets/Rooms/Level1/Hall.unity
  project/sherLOCKED/Assets/Rooms/Level1/Hall.unity.meta
  project/sherLOCKED/Assets/Rooms/Level1/Library.unity
  project/sherLOCKED/Assets/Rooms/Level1/Library.unity.meta
  project/sherLOCKED/Assets/Rooms/Level2.meta
  project/sherLOCKED/Assets/Rooms/Level2/ServerRoom 1.unity
  project/sherLOCKED/Assets/Rooms/Level2/ServerRoom 1.unity.meta
  project/sherLOCKED/Assets/Rooms/Level4.meta
  project/sherLOCKED/Assets/Rooms/Level4/BallroomL4.unity
  project/sherLOCKED/Assets/Rooms/Level4/BallroomL4.unity.meta
  project/sherLOCKED/Assets/Rooms/Level4/DiningRoomL4.unity
  project/sherLOCKED/Assets/Rooms/Level4/DiningRoomL4.unity.meta
  project/sherLOCKED/Assets/Rooms/Level4/HallL4.unity
  project/sherLOCKED/Assets/Rooms/Level4/HallL4.unity.meta
  project/sherLOCKED/Assets/Rooms/Level4/LibraryL4.unity
  project/sherLOCKED/Assets/Rooms/Level4/LibraryL4.unity.meta
  project/sherLOCKED/Assets/Rooms/Level4/ServerRoomL4.unity
  project/sherLOCKED/Assets/Rooms/Level4/ServerRoomL4.unity.meta
  project/sherLOCKED/Assets/Rooms/Misc.meta
  project/sherLOCKED/Assets/Rooms/Misc/LevelEnd.unity
  project/sherLOCKED/Assets/Rooms/Misc/LevelEnd.unity.meta
  project/sherLOCKED/Assets/Rooms/Misc/MainMenu.unity
  project/sherLOCKED/Assets/Rooms/Misc/MainMenu.unity.meta
  project/sherLOCKED/Assets/Rooms/Misc/_preload.unity
  project/sherLOCKED/Assets/Rooms/Misc/_preload.unity.meta
  project/sherLOCKED/Assets/Scripts/HallStart.cs
  project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
  project/sherLOCKED/Assets/Scripts/NPCs/NpcInteraction.cs
  project/sherLOCKED/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, gameplay, high priority

#147 Add credits to the main menu
  project/sherLOCKED/Assets/Rooms/Misc/MainMenu.unity
  project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
Labels: UI, enhancement, high priority

#142 Created case 3
  docs/planning/QuestionPlan.md
  project/sherLOCKED/Assets/Rooms/Level2/ServerRoom.unity
  project/sherLOCKED/Assets/Rooms/Level2/ServerRoom.unity.meta
  project/sherLOCKED/Assets/Rooms/Level3.meta
  project/sherLOCKED/Assets/Rooms/Level3/Ballroom_case3.unity
  project/sherLOCKED/Assets/Rooms/Level3/Ballroom_case3.unity.meta
  project/sherLOCKED/Assets/Rooms/Level3/DiningRoom_case3.unity
  project/sherLOCKED/Assets/Rooms/Level3/DiningRoom_case3.unity.meta
  project/sherLOCKED/Assets/Rooms/Level3/Hall_case3.unity
  project/sherLOCKED/Assets/Rooms/Level3/Hall_case3.unity.meta
  project/sherLOCKED/Assets/Rooms/Level3/Library_case3.unity
  project/sherLOCKED/Assets/Rooms/Level3/Library_case3.unity.meta
  project/sherLOCKED/Assets/Rooms/Level3/ServerRoom_case3.unity
  project/sherLOCKED/Assets/Rooms/Level3/ServerRoom_case3.unity.meta
  project/sherLOCKED/Assets/Rooms/Misc/MainMenu.unity
  project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
  project/sherLOCKED/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, gameplay

#148 Level end now reads correct deductions
  project/sherLOCKED/Assets/Rooms/Misc/LevelEnd.unity
Labels: bug, gameplay

#150 Fix wrong button changing colour RE #149
  project/sherLOCKED/Assets/Rooms/Misc/MainMenu.unity
  project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
Labels: bug, high priority

#158 Add project supervisor credit to main menu
  project/sherLOCKED/Assets/Rooms/Misc/MainMenu.unity
Labels: UI, enhancement

#159 Add a pause menu
  project/sherLOCKED/Assets/Rooms/Misc/MainMenu.unity
  project/sherLOCKED/Assets/Rooms/Misc/_preload.unity
  project/sherLOCKED/Assets/Scripts/Menus/PauseMenuController.cs
  project/sherLOCKED/Assets/Scripts/Menus/PauseMenuController.cs.meta
  project/sherLOCKED/Assets/Scripts/_preload/UIManager.cs
Labels: UI, enhancement, gameplay

#157 Fix glitchy text if npcs spoken to and e spammed
  project/sherLOCKED/Assets/Rooms/Level1/Hall.unity
  project/sherLOCKED/Assets/Scripts/UI/TextBoxController.cs
  project/sherLOCKED/Assets/UI/SpeechCanvas.prefab
Labels: bug, interactions

#160 Created conservatory
  project/sherLOCKED/Assets/Rooms/Level1/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Level1/Library.unity
  project/sherLOCKED/Assets/Rooms/Level2/ServerRoom.unity
  project/sherLOCKED/Assets/Rooms/Level3/DiningRoom_case3.unity
  project/sherLOCKED/Assets/Rooms/Level3/Library_case3.unity
  project/sherLOCKED/Assets/Rooms/Level4/Conservatory.unity
  project/sherLOCKED/Assets/Rooms/Level4/Conservatory.unity.meta
  project/sherLOCKED/Assets/Rooms/Level4/DiningRoomL4.unity
  project/sherLOCKED/Assets/Rooms/Level4/HallL4.unity
  project/sherLOCKED/Assets/Rooms/Level4/LibraryL4.unity
  project/sherLOCKED/Assets/Rooms/Level4/ServerRoomL4.unity
  project/sherLOCKED/Assets/Tiles/conservatory wall_window.asset
  project/sherLOCKED/Assets/Tiles/conservatory wall_window.asset.meta
  project/sherLOCKED/Assets/Tiles/conservatory wall_window.png
  project/sherLOCKED/Assets/Tiles/conservatory wall_window.png.meta
  project/sherLOCKED/Assets/Tiles/conservatory_floor.asset
  project/sherLOCKED/Assets/Tiles/conservatory_floor.asset.meta
  project/sherLOCKED/Assets/Tiles/conservatory_floor.png
  project/sherLOCKED/Assets/Tiles/conservatory_floor.png.meta
  project/sherLOCKED/Assets/Tiles/conservatory_wall_plain.asset
  project/sherLOCKED/Assets/Tiles/conservatory_wall_plain.asset.meta
  project/sherLOCKED/Assets/Tiles/conservatory_wall_plain.png
  project/sherLOCKED/Assets/Tiles/conservatory_wall_plain.png.meta
  project/sherLOCKED/Assets/Tiles/floors.prefab
  project/sherLOCKED/Assets/Tiles/walls.prefab
  project/sherLOCKED/ProjectSettings/EditorBuildSettings.asset
Labels: assets, enhancement, gameplay

#164 Fix Sherry appearing on main menu if pause menu is used
  project/sherLOCKED/Assets/Rooms/Level4/HallL4.unity
  project/sherLOCKED/Assets/Scripts/Menus/PauseMenuController.cs
Labels: UI, bug, gameplay, high priority

#165 Ensured all objects have box colliders
  project/sherLOCKED/Assets/Rooms/Level1/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Level1/Hall.unity
  project/sherLOCKED/Assets/Rooms/Level2/ServerRoom.unity
  project/sherLOCKED/Assets/Rooms/Level3/ServerRoom_case3.unity
  project/sherLOCKED/Assets/Rooms/Level4/HallL4.unity
  project/sherLOCKED/Assets/Rooms/Level4/ServerRoomL4.unity
Labels: assets

#168 Updated the minimap
  project/sherLOCKED/Assets/Rooms/Level4/Conservatory.unity
  project/sherLOCKED/Assets/UI/minimap.png
  project/sherLOCKED/Assets/UI/minimap_ballroom.png
  project/sherLOCKED/Assets/UI/minimap_conservatory.png
  project/sherLOCKED/Assets/UI/minimap_conservatory.png.meta
  project/sherLOCKED/Assets/UI/minimap_dining.png
  project/sherLOCKED/Assets/UI/minimap_hall.png
  project/sherLOCKED/Assets/UI/minimap_library.png
  project/sherLOCKED/Assets/UI/minimap_server.png
Labels: assets

#167 Return to level select when completing level
  project/sherLOCKED/Assets/Rooms/Misc/MainMenu.unity
  project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
  project/sherLOCKED/Assets/Scripts/UI/LevelEnd.cs
  project/sherLOCKED/Assets/Scripts/_preload/UIManager.cs
Labels: UI, bug

#169 Fix start menu by enabling all objects RE #NONE
  project/sherLOCKED/Assets/Rooms/Misc/MainMenu.unity
Labels: UI, bug, high priority

#171 Fix a bug where ginny's question would not disappear RE #NONE
  project/sherLOCKED/Assets/Scripts/UI/QuestionController.cs
Labels: UI, bug, hotfix
