Repository ConorMFinn/CO600-SeriousCyberSec, pull requests merged in 2021-01, with the labels that each got.

#52 Make UI Scale according to screen size RE #51
  project/sherLOCKED/Assets/Rooms/Hall.unity
Labels: bug

#59 Fix Sherry and Desk Hitboxes
  project/sherLOCKED/Assets/Rooms/Hall.unity
Labels: bug

#60 47 interaction asset
  assets/psd/interaction_ui.psd
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Scripts/Sherry/SherryInteract.cs
  project/sherLOCKED/Assets/UI/interactionSymbol.png
  project/sherLOCKED/Assets/UI/interactionSymbol.png.meta
Labels: enhancement

#71 Add Victim (Ginny) to the game.
  assets/characters/ginny/ginny.png
  assets/psd/ginny.psd
  project/sherLOCKED/Assets/Characters/ginny.png
  project/sherLOCKED/Assets/Characters/ginny.png.meta
  project/sherLOCKED/Assets/Rooms/Hall.unity
Labels: enhancement

#68 Create questions for level 1
  docs/planning/QuestionPlan.md
Labels: documentation

#76 meeting
  docs/meetings/2021-01-12_MeetingMinutes.md
Labels: meetings

#78 Make ginny face the player when interacting
  project/sherLOCKED/Assets/Animations/ginny_east.anim
  project/sherLOCKED/Assets/Animations/ginny_east.anim.meta
  project/sherLOCKED/Assets/Animations/ginny_north.anim
  project/sherLOCKED/Assets/Animations/ginny_north.anim.meta
  project/sherLOCKED/Assets/Animations/ginny_south.anim
  project/sherLOCKED/Assets/Animations/ginny_south.anim.meta
  project/sherLOCKED/Assets/Animations/ginny_west.anim
  project/sherLOCKED/Assets/Animations/ginny_west.anim.meta
  project/sherLOCKED/Assets/Animations/npc_ac.controller
  project/sherLOCKED/Assets/Animations/npc_ac.controller.meta
  project/sherLOCKED/Assets/Characters/ginny.prefab
  project/sherLOCKED/Assets/Characters/ginny.prefab.meta
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Scripts/NPCs.meta
  project/sherLOCKED/Assets/Scripts/NPCs/NpcInteraction.cs
  project/sherLOCKED/Assets/Scripts/NPCs/NpcInteraction.cs.meta
  project/sherLOCKED/ProjectSettings/GraphicsSettings.asset
Labels: enhancement, interactions

#72 Add progress bars to the game
  project/sherLOCKED/Assets/Animations/npc_ac.controller
  project/sherLOCKED/Assets/Characters/ginny.prefab
  project/sherLOCKED/Assets/Characters/sherry_b1.prefab
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Scripts/Objects/ComputerInteraction.cs
  project/sherLOCKED/Assets/Scripts/Sherry/SherryProgress.cs
  project/sherLOCKED/Assets/Scripts/Sherry/SherryProgress.cs.meta
  project/sherLOCKED/Assets/Scripts/UI.meta
  project/sherLOCKED/Assets/Scripts/UI/ProgressBar.cs
  project/sherLOCKED/Assets/Scripts/UI/ProgressBar.cs.meta
  project/sherLOCKED/Assets/UI/ProgressCanvas.prefab
  project/sherLOCKED/Assets/UI/ProgressCanvas.prefab.meta
  project/sherLOCKED/Assets/UI/progressBar.png
  project/sherLOCKED/Assets/UI/progressBar.png.meta
Labels: UI, enhancement, interactions

#82 Added new map idea
  docs/planning/MapPlan.jpeg
Labels: documentation

#80 Add a gameplay introduction
  docs/planning/IntroScript.txt
  project/sherLOCKED/.vscode/launch.json
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Scripts/NPCs/NpcInteraction.cs
  project/sherLOCKED/Assets/Scripts/UI/TextBoxController.cs
  project/sherLOCKED/Assets/Scripts/UI/TextBoxController.cs.meta
  project/sherLOCKED/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  project/sherLOCKED/Assets/UI/SpeechCanvas.prefab
  project/sherLOCKED/Assets/UI/SpeechCanvas.prefab.meta
  project/sherLOCKED/Assets/UI/Thaleah_DemoBackground.png
  project/sherLOCKED/Assets/UI/Thaleah_DemoBackground.png.meta
Labels: UI, enhancement, interactions

#87 Adding connections between doors
  project/sherLOCKED/Assets/Objects/door_closed.png
  project/sherLOCKED/Assets/Objects/door_closed.png.meta
  project/sherLOCKED/Assets/Objects/door_open.png
  project/sherLOCKED/Assets/Objects/door_open.png.meta
  project/sherLOCKED/Assets/Rooms/Ballroom.unity
  project/sherLOCKED/Assets/Rooms/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Rooms/Library.unity
  project/sherLOCKED/Assets/Scripts/HallStart.cs
  project/sherLOCKED/Assets/Scripts/HallStart.cs.meta
  project/sherLOCKED/Assets/Scripts/Objects/DoorInteraction.cs
  project/sherLOCKED/Assets/Scripts/Objects/DoorInteraction.cs.meta
  project/sherLOCKED/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#92 Fix General Bugs
  project/sherLOCKED/Assets/Rooms/Ballroom.unity
  project/sherLOCKED/Assets/Rooms/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Rooms/Library.unity
  project/sherLOCKED/Assets/Rooms/ServerRoom.unity
  project/sherLOCKED/Assets/Scripts/HallStart.cs
  project/sherLOCKED/Assets/Scripts/UI/TextBoxController.cs
  project/sherLOCKED/Assets/UI/QuestionCanvas.prefab
Labels: bug, gameplay

#93 Created Global Score Manager
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Rooms/_preload.unity
  project/sherLOCKED/Assets/Rooms/_preload.unity.meta
  project/sherLOCKED/Assets/Scripts/Objects/BoxInteraction.cs
  project/sherLOCKED/Assets/Scripts/Objects/ComputerInteraction.cs
  project/sherLOCKED/Assets/Scripts/Objects/ObjectInteraction.cs
  project/sherLOCKED/Assets/Scripts/UI/QuestionController.cs
  project/sherLOCKED/Assets/Scripts/UI/QuestionController.cs.meta
  project/sherLOCKED/Assets/Scripts/_preload.meta
  project/sherLOCKED/Assets/Scripts/_preload/BeginGame.cs
  project/sherLOCKED/Assets/Scripts/_preload/BeginGame.cs.meta
  project/sherLOCKED/Assets/Scripts/_preload/DDOL.cs
  project/sherLOCKED/Assets/Scripts/_preload/DDOL.cs.meta
  project/sherLOCKED/Assets/Scripts/_preload/ScoreManager.cs
  project/sherLOCKED/Assets/Scripts/_preload/ScoreManager.cs.meta
  project/sherLOCKED/Assets/UI/ProgressCanvas.prefab
Labels: enhancement, gameplay

#97 Made the dining table shorter
  project/sherLOCKED/Assets/Objects/diningTable.png
Labels: assets

#98 Create question plan
  docs/planning/QuestionPlan.md
Labels: documentation

#99 Ready for WebGL export
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Rooms/PreHall.unity
  project/sherLOCKED/Assets/Rooms/PreHall.unity.meta
  project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
  project/sherLOCKED/Assets/Scripts/UI/UIStart.cs
  project/sherLOCKED/Assets/Scripts/UI/UIStart.cs.meta
  project/sherLOCKED/ProjectSettings/EditorBuildSettings.asset
  project/sherLOCKED/ProjectSettings/TagManager.asset
Labels: UI, bug

#101 Added Global Question Tracking
  project/sherLOCKED/Assets/Rooms/Ballroom.unity
  project/sherLOCKED/Assets/Rooms/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Rooms/Library.unity
  project/sherLOCKED/Assets/Rooms/_preload.unity
  project/sherLOCKED/Assets/Scripts/Objects/ObjectInteraction.cs
  project/sherLOCKED/Assets/Scripts/Sherry/SherryInteract.cs
  project/sherLOCKED/Assets/Scripts/_preload/QuestionManager.cs
  project/sherLOCKED/Assets/Scripts/_preload/QuestionManager.cs.meta
  project/sherLOCKED/Assets/Scripts/_preload/ScoreManager.cs
Labels: bug, interactions

#100 Created a new carpet for each room
  assets/tiles/ballroom_carpet.png
  assets/tiles/dining_carpet.png
  assets/tiles/library_carpet.png
  project/sherLOCKED/Assets/Rooms/Ballroom.unity
  project/sherLOCKED/Assets/Rooms/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Library.unity
  project/sherLOCKED/Assets/Tiles/ballroom_carpet.asset
  project/sherLOCKED/Assets/Tiles/ballroom_carpet.asset.meta
  project/sherLOCKED/Assets/Tiles/ballroom_carpet.png
  project/sherLOCKED/Assets/Tiles/ballroom_carpet.png.meta
  project/sherLOCKED/Assets/Tiles/dining_carpet.asset
  project/sherLOCKED/Assets/Tiles/dining_carpet.asset.meta
  project/sherLOCKED/Assets/Tiles/dining_carpet.png
  project/sherLOCKED/Assets/Tiles/dining_carpet.png.meta
  project/sherLOCKED/Assets/Tiles/floors.prefab
  project/sherLOCKED/Assets/Tiles/library_carpet.asset
  project/sherLOCKED/Assets/Tiles/library_carpet.asset.meta
  project/sherLOCKED/Assets/Tiles/library_carpet.png
  project/sherLOCKED/Assets/Tiles/library_carpet.png.meta
Labels: assets

#102 WIP: Create Level end scene
  assets/UI/closed_stamp.png
  assets/UI/notebook.png
  assets/psd/end_screen.psd
  project/sherLOCKED/Assets/Rooms/LevelEnd.unity
  project/sherLOCKED/Assets/Rooms/LevelEnd.unity.meta
  project/sherLOCKED/Assets/Rooms/PreHall.unity
  project/sherLOCKED/Assets/Rooms/_preload.unity
  project/sherLOCKED/Assets/Scripts/HallStart.cs
  project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
  project/sherLOCKED/Assets/Scripts/Sherry/SherryInteract.cs
  project/sherLOCKED/Assets/Scripts/UI/LevelEnd.cs
  project/sherLOCKED/Assets/Scripts/UI/LevelEnd.cs.meta
  project/sherLOCKED/Assets/Scripts/UI/UIStart.cs
  project/sherLOCKED/Assets/Scripts/_preload/ScoreManager.cs
  project/sherLOCKED/Assets/Scripts/_preload/UIManager.cs
  project/sherLOCKED/Assets/Scripts/_preload/UIManager.cs.meta
  project/sherLOCKED/Assets/UI/closed_stamp.png
  project/sherLOCKED/Assets/UI/closed_stamp.png.meta
  project/sherLOCKED/Assets/UI/notebook.png
  project/sherLOCKED/Assets/UI/notebook.png.meta
  project/sherLOCKED/ProjectSettings/EditorBuildSettings.asset
Labels: assets, enhancement, gameplay

#107 Created minimap
  ProjectSettings/ProjectVersion.txt
  project/sherLOCKED/Assets/Rooms/Ballroom.unity
  project/sherLOCKED/Assets/Rooms/DiningRoom.unity
  project/sherLOCKED/Assets/Rooms/Hall.unity
  project/sherLOCKED/Assets/Rooms/Library.unity
  project/sherLOCKED/Assets/Rooms/ServerRoom.unity
  project/sherLOCKED/Assets/UI/minimap.png
  project/sherLOCKED/Assets/UI/minimap.png.meta
  project/sherLOCKED/Assets/UI/minimap_ballroom.png
  project/sherLOCKED/Assets/UI/minimap_ballroom.png.meta
  project/sherLOCKED/Assets/UI/minimap_dining.png
  project/sherLOCKED/Assets/UI/minimap_dining.png.meta
  project/sherLOCKED/Assets/UI/minimap_hall.png
  project/sherLOCKED/Assets/UI/minimap_hall.png.meta
  project/sherLOCKED/Assets/UI/minimap_library.png
  project/sherLOCKED/Assets/UI/minimap_library.png.meta
  project/sherLOCKED/Assets/UI/minimap_server.png
  project/sherLOCKED/Assets/UI/minimap_server.png.meta
  project/sherLOCKED/ProjectSettings/TagManager.asset
Labels: assets, enhancement

#110 Created Simmer.io Build
  project/sherLOCKED/Assets/Scripts/HallStart.cs
  project/sherLOCKED/Assets/Scripts/Objects/DoorInteraction.cs
  project/sherLOCKED/ProjectSettings/EditorBuildSettings.asset
  project/sherLOCKED/ProjectSettings/GraphicsSettings.asset
  project/sherLOCKED/ProjectSettings/ProjectSettings.asset
Labels: bug, enhancement, high priority
